### ISSUE TITLE
slight problem

### ISSUE THREAD

**Issue by monalisa62003** [ali-dev-code/login-system#1]
hey this is great but when you open it first up it says logout instead of login? odd

**Comment by monalisa62003** [comment]
i got that to work but how do i load a users profile?cant seem to echo out anything?

**Comment by ali-dev-code** [comment]
> I got that to work but how do I load a user profile? can't seem to echo out anything?

you can easily fetch user profile data through user session that we use to check which user is online

**Comment by monalisa62003** [comment]
Sorry I'm slightly new to this

Could only get email to show;(

**Comment by monalisa62003** [comment]
i dont know why this keeps happening. i do session email whatever it is it doesnt work on this one then i go to another login script and it worked once but then hasnt worked since i started messing with it. so i go back to the original and it still doesnt work. im using the same thing but it never seems to work with email only username?

**Comment by ali-dev-code** [comment]
> i dont know why this keeps happening. i do session email whatever it is it doesnt work on this one then i go to another login script and it worked once but then hasnt worked since i started messing with it. so i go back to the original and it still doesnt work. im using the same thing but it never seems to work with email only username?

What 
ali.asgr514@gmail.com

**Comment by ali-dev-code** [comment]
> I don't know why this keeps happening. I do session email whatever it is it doesn't work on this one then i go to another login script and it worked once but then hasn't worked since i started messing with it. so I go back to the original and it still doesn't work. I'm using the same thing but it never seems to work with email only username?

hello again!
email me here. and explain what you need I will send you working
ali.asgr514@mail.com
